#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_security_login:
  path: /login
  controller: App\Controller\SecurityController::loginAction
  options:
    expose: true
fos_user_security_check:
  path: /login_check
  controller: App\Controller\SecurityController::loginAction
  options:
    expose: true
demo:
  path:       /demo
  controller: App\Controller\SecurityController::demo